server:
  port: 9000

spring:
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: "postgres"
      password: "pg123456"
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
