server:
  port: 9000
spring:
  profiles:
    active: prod-test
---
spring:
  profiles: local
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
---
spring:
  profiles: prod
  datasource:
    url: "jdbc:postgresql://hattie.db.elephantsql.com:5432/ogqaofff"
    username: "ogqaofff"
    password: "J0q2m9A8Q-qxuSR1BvhhggpXehmGHgpP"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
---
spring:
  profiles: prod-test
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "pg123456"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create