drop table if exists account CASCADE;
drop table if exists customer CASCADE;
drop table if exists customers_employers CASCADE;
drop table if exists employer CASCADE;
drop table if exists r_customer_account CASCADE;

create table customer
(
    customer_id int not null generated by default as identity,
    age         int,
    email       varchar(255),
    name        varchar(255),
    primary key (customer_id)
);

create table account
(
    account_id           int not null generated by default as identity,
    balance              double,
    currency             varchar(255),
    number               varchar(255),
    customer_customer_id int,
    primary key (account_id),
    foreign key (customer_customer_id) references customer (customer_id)
);

create table employer
(
    employer_id int not null generated by default as identity,
    address     varchar(255),
    name        varchar(255),
    primary key (employer_id)
);

create table customers_employers
(
    cus_id int not null,
    emp_id int not null,
    foreign key (cus_id) references customer (customer_id),
    foreign key (emp_id) references employer (employer_id)
);

create table r_customer_account
(
    cus_id int not null,
    acc_id int not null,
    constraint account_id_unique unique (acc_id),
    foreign key (acc_id) references account (account_id),
    foreign key (cus_id) references customer (customer_id)
);

insert into customer (age, email, name) values (21, 'customer1@gmail.com', 'name1');
insert into customer (age, email, name) values (22, 'customer2@gmail.com', 'name2');
insert into customer (age, email, name) values (23, 'customer3@gmail.com', 'name3');
insert into account (balance, currency, number, customer_customer_id) values (0.0, 'USD', '123', 1);
insert into account (balance, currency, number, customer_customer_id) values (0.0, 'USD', '124', 1);
insert into account (balance, currency, number, customer_customer_id) values (0.0, 'USD', '125', 1);