#CUSTOMER API
###
GET http://localhost:9000/customer/all
###
GET http://localhost:9000/customer?id=2
###
POST http://localhost:9000/customer/create
Content-Type: application/json

{
  "name": "customer2",
  "email": "customer2 email",
  "age": 22
}
###
POST http://localhost:9000/customer/create
Content-Type: application/json

{
  "name": "rich",
  "email": "rich email",
  "age": 57
}
###
POST http://localhost:9000/customer/accounts/create?id=9&currency=USD
###
POST http://localhost:9000/customer/accounts/create?id=1&currency=UAH
###
PUT http://localhost:9000/customer/modify?id=1
Content-Type: application/json

{
  "name": "customer1 modified",
  "email": "customer1 email modified",
  "age": 1
}
###
DELETE http://localhost:9000/customer/accounts/delete?id=2
###
DELETE http://localhost:9000/customer/delete?id=2

#-----------------------------------------------------------------------------------------------------
###ACCOUNT API
###
PUT http://localhost:9000/account/put?accountNumber=8187351f-9579-416b-b879-a729282f3ced&sum=1000
###
PUT http://localhost:9000/account/withdraw?accountNumber=USD111&sum=117
###
PUT http://localhost:9000/account/transfer?from=8187351f-9579-416b-b879-a729282f3ced&to=6cf66400-ddba-4390-b68d-04aff854e316&sum=234
#-----------------------------------------------------------------------------------------------------
###EMPLOYER API
###
###
###
GET http://localhost:9000/employer?id=1

###
GET http://localhost:9000/employer/all

###
POST http://localhost:9000/employer/create
Content-Type: application/json

{
  "name": "employer1",
  "address": "employer1 addresss"
}

###
PUT http://localhost:9000/employer/modify/1
Content-Type: application/json

{
  "name": "employer modified 2",
  "address": "employer1 addresss modified 2"
}

###
DELETE http://localhost:9000/employer/delete/1